name: Continuous Integration

# ----------------------------------------------------------
# Définition des événements qui déclenchent le workflow :
#  - quand on pousse du code sur main
#  - quand on crée une pull request vers main
# ----------------------------------------------------------
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# ----------------------------------------------------------
# Début de la section des "jobs" (tâches automatiques)
# ----------------------------------------------------------
jobs:
  # ==========================================================
  # Job principal : CI du back-end
  # ==========================================================
  backend_ci:
    name: Backend - Build, Test, Sonar
    runs-on: ubuntu-latest  # Machine virtuelle Linux utilisée par GitHub

    # Définit que toutes les commandes se lanceront depuis le dossier /back
    defaults:
      run:
        working-directory: back

    steps:
      # ------------------------------------------------------
      # Étape 1 : Récupère le code source depuis le repo GitHub
      # ------------------------------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # ------------------------------------------------------
      # Étape 2 : Installe Java 11 (le projet utilise Java 11)
      # ------------------------------------------------------
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'  # Version Java spécifiée dans le pom.xml
          cache: maven        # Cache Maven pour accélérer les builds

      # ------------------------------------------------------
      # Étape 3 : Compile et lance les tests du back-end
      #  - mvn clean verify => compile, exécute les tests
      # ------------------------------------------------------
      - name: Build & test (Maven)
        run: mvn -B -q clean verify

      # ------------------------------------------------------
      # Étape 4 : Analyse de qualité avec SonarCloud
      #  - Envoie les résultats de tests et de couverture
      #  - Nécessite les 4 secrets GitHub configurés :
      #    SONAR_TOKEN / SONAR_ORG / SONAR_PROJECT_KEY_BACK / SONAR_HOST_URL
      # ------------------------------------------------------
      - name: SonarCloud analysis
        run: |
          mvn -B -q sonar:sonar \
            -Dsonar.organization=${{ secrets.SONAR_ORG }} \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY_BACK }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

  # ==========================================================
  # Job optionnel : vérifie le code du front-end (lint)
  #     Ce job est "non bloquant" : même s’il échoue, la pipeline continue
  # ==========================================================
  frontend_lint:
    name: Frontend - Lint (non bloquant)
    runs-on: ubuntu-latest
    continue-on-error: true  # Ne bloque pas la pipeline s’il échoue

    # Toutes les commandes se lancent depuis le dossier /front
    defaults:
      run:
        working-directory: front

    steps:
      # ------------------------------------------------------
      # Étape 1 : Récupère le code du repo
      # ------------------------------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # ------------------------------------------------------
      # Étape 2 : Installe Node.js 18 pour exécuter npm
      # ------------------------------------------------------
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # ------------------------------------------------------
      # Étape 3 : Installe les dépendances du projet front
      # ------------------------------------------------------
      - name: Install deps
        run: npm ci || npm install

      # ------------------------------------------------------
      # Étape 4 : Lance la commande de lint
      #  - Vérifie la qualité du code front (erreurs de style, syntaxe, etc.)
      #  - Si le projet n’a pas de script "lint", on ignore sans erreur
      # ------------------------------------------------------
      - name: Lint
        run: npm run lint || echo "No lint script, skipping"
