# Ce fichier est un workflow GitHub Actions qui exécute le lint du frontend avec eslint
#
# Il est déclenché par un autre workflow (workflow_call) et
# utilise le cache GitHub Actions pour optimiser le processus
#
# Jobs :
# - lint-frontend : exécute le lint du frontend
#

name: Linting Frontend

# Ce workflow est déclenché lorsqu'il est appelé par un autre workflow
on:
  workflow_call:

# Définition des jobs à exécuter dans ce workflow
jobs:

  # Exécute le lint du frontend
  lint-frontend:
    name: Frontend linting
    # S'exécute sur un runner avec une version d'Ubuntu récente
    runs-on: ubuntu-latest

    # Étapes de ce job
    steps:

      # Étape 1 : Récupérer le code du dépôt avec Git
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Récupère seulement le dernier commit
          fetch-depth: 1

      # Étape 2 : Récupérer le cache de npm
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ github.ref_name }}
          restore-keys: ${{ runner.os }}-node

      # Étape 3 : Installer Node.js 18 et récupérer le cache de npm
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Étape 4 : Installer les dépendances du projet
      - name: Install dependencies
        run: npm ci --no-audit --progress=false
        working-directory: front

      # Étape 5 : Exécuter le lint avec eslint
      - name: Run ESLint (Fail on violations)
        run: npm run lint
        working-directory: front

      # Étape 6 : Générer le rapport eslint
      - name: Generate ESLint Report
        run: npm run lint:ci
        working-directory: front

      # Étape 7 : Envoyer le rapport eslint
      - name: Upload ESLint Report
        uses: actions/upload-artifact@v4
        with:
          # Nom de l'artefact qui sera créé
          name: eslint-report
          path: front/reports/eslint_report.json

      # Étape 8 : Analyser le rapport eslint
      - name: Process ESLint report
        uses: ataylorme/eslint-annotate-action@v2
        if: github.ref_name != 'main'
        with:
          report-json: front/reports/eslint_report.json
          fail-on-warning: false
          check-name: Frontend Linting Report
